#!/usr/bin/env python3
"""Skip governance: enforce max_skips threshold in CI.

Reads the JUnit XML report generated by pytest and checks the total
number of skipped tests. Fails with a non-zero exit code if the skip
count exceeds MAX_SKIPS.

This prevents test-suite decay where developers paper over broken
tests with @pytest.mark.skip instead of fixing them.
"""

import sys
import xml.etree.ElementTree as ET
from pathlib import Path

MAX_SKIPS = 3
REPORT_PATH = Path("results/junit/checks-report.xml")
ALT_REPORT_PATHS = [
    Path("results/junit/release-integrity-report.xml"),
]


def count_skips(report_path: Path) -> int | None:
    """Parse JUnit XML and return skip count. Returns None if file missing."""
    if not report_path.exists():
        return None
    tree = ET.parse(report_path)
    root = tree.getroot()
    skip_count = 0
    for testsuite in root.iter("testsuite"):
        skip_count += int(testsuite.get("skips", 0))
    # Also count individual skipped testcases
    for testcase in root.iter("testcase"):
        for child in testcase:
            if child.tag in ("skipped", "skip"):
                skip_count += 1
    return skip_count


def main() -> None:
    report_paths = [REPORT_PATH] + ALT_REPORT_PATHS
    total_skips = 0
    found = False

    for rp in report_paths:
        count = count_skips(rp)
        if count is not None:
            print(f"SKIP-GOVERNANCE: {rp} — {count} skipped tests")
            total_skips += count
            found = True

    if not found:
        print("SKIP-GOVERNANCE: ERROR — no JUnit report found at any expected path")
        for rp in report_paths:
            print(f"  Checked: {rp.resolve() if rp.exists() else rp}")
        sys.exit(1)

    print(f"SKIP-GOVERNANCE: Total skipped tests: {total_skips}")
    print(f"SKIP-GOVERNANCE: Max allowed: {MAX_SKIPS}")

    if total_skips > MAX_SKIPS:
        print(f"SKIP-GOVERNANCE: FAIL — {total_skips} skips exceeds max of {MAX_SKIPS}")
        print(f"SKIP-GOVERNANCE: Action required: Fix or remove {total_skips - MAX_SKIPS} skipped test(s)")
        sys.exit(1)

    print(f"SKIP-GOVERNANCE: PASS — {total_skips} <= {MAX_SKIPS}")


if __name__ == "__main__":
    main()
