"""Shared contract schemas and validation utilities for HELIX-IDS."""

from .attack_taxonomy import (
    ATTACK_FAMILIES,
    ATTACK_TAXONOMY_7CLASS,
    CICIDS2018_TO_7CLASS,
    CICIDS_TO_7CLASS,
    CICIDS_TO_UNIFIED_5CLASS,
    FAMILY_INDEX_TO_NAME,
    FAMILY_TO_INDEX,
    HELIX_CLASS_TO_INDEX,
    HELIX_CLASSES,
    NSL_KDD_ATTACK_MAPPING,
    NSLKDD_TO_7CLASS,
    SEVEN_CLASS_THREAT_WEIGHTS,
    THREAT_WEIGHTS,
    UNIFIED_5CLASS,
    UNSW_TO_7CLASS,
    UNSW_TO_UNIFIED_5CLASS,
    assert_mapping_covers,
    get_all_family_names,
    resolve_family,
    threat_weight_tensor,
    validate_family,
)
from .diagnostic_contract import (
    DECISION_MODES,
    DECISION_TRANSITIONS,
    DiagnosticContract,
    enforce_decision_transition,
    migrate_contract_payload,
    validate_diagnostic_contract,
)
from .immutable_constants import (
    CONTRACT_VERSION,
    EXPORTER_API_VERSION,
    FEATURE_ORDER_HASH,
    MANIFEST_VERSION,
    SCHEMA_HASH,
)
from .schema_contract import (
    CANONICAL_BINARY_CLASSES,
    CANONICAL_FAMILY_CLASSES,
    CANONICAL_FEATURE_ORDER,
    CANONICAL_INPUT_DIM,
    SCHEMA_VERSION,
    assert_runtime_contract,
    compute_schema_hash,
    runtime_contract_payload,
    validate_feature_order,
)

__all__ = [
    "CANONICAL_FEATURE_ORDER",
    "CANONICAL_INPUT_DIM",
    "CANONICAL_BINARY_CLASSES",
    "CANONICAL_FAMILY_CLASSES",
    "SCHEMA_VERSION",
    "SCHEMA_HASH",
    "FEATURE_ORDER_HASH",
    "compute_schema_hash",
    "validate_feature_order",
    "assert_runtime_contract",
    "runtime_contract_payload",
    "CONTRACT_VERSION",
    "EXPORTER_API_VERSION",
    "MANIFEST_VERSION",
    "DECISION_TRANSITIONS",
    "DECISION_MODES",
    "DiagnosticContract",
    "enforce_decision_transition",
    "migrate_contract_payload",
    "validate_diagnostic_contract",
    # Attack taxonomy
    "ATTACK_FAMILIES",
    "ATTACK_TAXONOMY_7CLASS",
    "FAMILY_TO_INDEX",
    "FAMILY_INDEX_TO_NAME",
    "THREAT_WEIGHTS",
    "threat_weight_tensor",
    "NSL_KDD_ATTACK_MAPPING",
    "UNSW_TO_UNIFIED_5CLASS",
    "CICIDS_TO_UNIFIED_5CLASS",
    "HELIX_CLASSES",
    "HELIX_CLASS_TO_INDEX",
    "SEVEN_CLASS_THREAT_WEIGHTS",
    "NSLKDD_TO_7CLASS",
    "UNSW_TO_7CLASS",
    "CICIDS_TO_7CLASS",
    "CICIDS2018_TO_7CLASS",
    "get_all_family_names",
    "validate_family",
    "resolve_family",
    "assert_mapping_covers",
]
